### ISSUE TITLE
Information about external Elements in the case of an Element without Collection

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#432] opened 2023-07-24 08:44 UTC
Here is the current JSON-LD example of a single `Annotation` element:
```
{
  "@context": "https://spdx.github.io/spdx-3-model/rdf/context.json",
  "type": "Annotation",
  "spdxId": "http://spdx.acme.org/3FA9CB25#annotation34",
  "creationInfo": {
    "type": "CreationInfo",
    "specVersion": "3.0.0",
    "created": "2022-12-01T00:00:00Z",
    "createdBy": ["https://spdx.dev/elements/3F26391C#spdx-dev"],
    "profile": ["core"],
    "dataLicense": "https://spdx.org/licenses/CC0-1.0"
  },
  "name": "Acme Corp. Super SBOM-o-lator",
  "annotationType": "review",
  "subject": "http://spdx.acme.org/3FA9CB25#person9",
  "contentType": "text/plain",
  "statement": "Keanu Reeves is back as cyberpunk icon Neo but fans of the original will find this cynical reboot a bitter pill to swallow."
}
```
If this were part of an `ElementCollection`, then the two external `spdxId`s `https://spdx.dev/elements/3F26391C#spdx-dev` and `http://spdx.acme.org/3FA9CB25#person9` would be part of the `imports` property of the collection, which is an `ExternalMap` that gives information on where to find these Elements. In the case of the Annotation being a single Element in the payload not part of any collection, this additional information cannot currently be expressed. Is this an oversight or intended behavior? If the latter, I'm wondering why a collection provides more information than a single Element.

**Comment by davaya** [comment] 2023-07-24 14:40
Related to #415.

* ElementCollection is a logical concept.
* Payload is a physical concept.

If there is an ElementCollection (Bom/Sbom) `https://spdx.dev/elements/3F26391C#sbom99` listing three members
- `http://spdx.acme.org/3FA9CB25#annotation34`
- `https://spdx.dev/elements/3F26391C#spdx-dev`
- `http://spdx.acme.org/3FA9CB25#person9`

there can be 1, 2, 3, or 4 physical payloads carrying their values.
If it's one payload, no problem, there are no "external" elements to be imported from another payload.
If it's two payloads: payload1 = [sbom99, spdx-dev, person9], payload2 = [annotation34], then payload1 could contain a fourth element of type SpdxDocument allowing elements in payload2 to be located, verified, and "imported".

This allows the minter of payload1 to bind the content of payload2 that existed at the time payload1 was minted.

Payload2 containing just annotation34 can be serialized individually with no need to import any elements that it references.

**Comment by sbarnum** [comment] 2023-08-08 15:15
@armintaenzertng Yes it was an intentional design decision. I concur with your observation and agree with your concern.
Originally, we had ExternalMap and NamespaceMap expressed on Element which would alleviate the sorts of granularity concerns you raise here.
Group consensus (with me a yielding dissenter) was that this had the potential to be too verbose and a compromise was to place ExternalMap and NamespaceMap on ElementCollection (called just Collection at the time).

I do not agree that ExternalMap intended or limited in scope to only serialization or "payload" concerns. It serves use cases beyond only serialization.

**Comment by goneall** [comment] 2023-08-08 17:54
> I do not agree that ExternalMap intended or limited in scope to only serialization or "payload" concerns. It serves use cases beyond only serialization.

@sbarnum - can you articulate the additional use cases?  This will help with the follow-up meeting on the namespace maps.

**Comment by goneall** [comment] 2023-09-19 17:06
Closing this issue - it is intended behavior.

**Closed** 2023-09-19 17:07 UTC
Labels: Profile:Core
