### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#174] opened 2023-04-04 18:25 UTC
The most recent build merging in PR #170 failed with the following:

```
...
16:45:22 ERROR riot            :: Not found: file:///tmp/spec-parser.out/tst.ttl
org.apache.jena.riot.RiotException: Not found: file:///tmp/spec-parser.out/tst.ttl
	at riotcmd.ErrorHandlerCLI.error(ErrorHandlerCLI.java:65)
	at riotcmd.CmdLangParse.parseRIOT(CmdLangParse.java:333)
	at riotcmd.CmdLangParse.parseFile(CmdLangParse.java:277)
	at riotcmd.CmdLangParse.exec$(CmdLangParse.java:175)
	at riotcmd.CmdLangParse.exec(CmdLangParse.java:135)
	at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:87)
	at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:56)
	at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:43)
	at riotcmd.riot.main(riot.java:29)
Error: Process completed with exit code 2.
```

**Comment by zvr** [comment] 2023-04-04 20:37
If it's running `spec-parser`, it would fail since the change to understand "External properties restrictions" has not been merged yet: https://github.com/spdx/spec-parser/pull/39

**Comment by maxhbr** [comment] 2023-04-07 20:39
as @zvr correctly pointed out, the error is happening earlier in the spec parser, which fails but still exits on `0`:

see https://github.com/spdx/spdx-3-model/actions/runs/4634281022/jobs/8200331086, the errors are:

```
Run cd spec-parser
ERROR   : ../model/Software/Classes/File.md:Ln 32,Col 2: Syntax Error
	 Line no 32: '##'
ERROR   : Unable to parse `Class` markdown: '../model/Software/Classes/File.md'
ERROR   : ../model/Software/Classes/Package.md:Ln 55,Col 2: Syntax Error
	 Line no 55: '##'
ERROR   : Unable to parse `Class` markdown: '../model/Software/Classes/Package.md'
ERROR   : ../model/Build/Classes/Build.md:Ln 49,Col 2: Syntax Error: Expected `<key>: <values>`
	 Line no 49: '  - minCount:0\n'
ERROR   : ../model/Build/Classes/Build.md:Ln 50,Col 2: Syntax Error: Expected `<key>: <values>`
	 Line no 50: '  - maxCount:1\n'
ERROR   : ../model/Build/Classes/Build.md:Ln 53,Col 2: Syntax Error: Expected `<key>: <values>`
	 Line no 53: '  - minCount:0\n'
ERROR   : ../model/Build/Classes/Build.md:Ln 54,Col 2: Syntax Error: Expected `<key>: <values>`
	 Line no 54: '  - maxCount:1\n'
ERROR   : Unable to parse `Class` markdown: '../model/Build/Classes/Build.md'
ERROR   : ../model/Core/Classes/SpdxDocument.md:Ln 27,Col 2: Syntax Error
	 Line no 27: '##'
ERROR   : Unable to parse `Class` markdown: '../model/Core/Classes/SpdxDocument.md'
WARNING : skipping ../model/Core/Properties/_property.md
WARNING : skipping ../model/Core/Vocabularies/_vocab.md
WARNING : Specs not parsed succesfully, aborting the gen_md...
WARNING : https://spdx.org/rdf/Build#map<string>string does not look like a valid URI, trying to serialize this will break.
WARNING : https://spdx.org/rdf/Build#map<string>string does not look like a valid URI, trying to serialize this will break.
WARNING : Error parsing the spec. Aborting the gen_rdf...
```

**Comment by zvr** [comment] 2023-04-07 22:28
Yes, besides the spec-parser not handling the new section, the issue is that the build profile that was recently merged does not use correct syntax (all the map stuff, etc.).

I assume the thinking was that it was ok for the merge to go ahead since the model was finished, and syntax stuff can be fixed in the main branch.

**Comment by kestewart** [comment] 2023-04-30 11:37
I think this has been resolved, however if this is not the case,  please reopen with updated status and assign someone to work on it.

**Closed by kestewart** 2023-04-30 11:37 UTC
