### ISSUE TITLE
Licensing: Align meanings of isFsfLibre and isOsiApproved

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#212] opened 2023-04-16 12:12 UTC
Relates to #211

Currently, in the context of the License List, isFsfLibre and isOsiApproved have different meanings. From https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md:

> **E) OSI Approved?**
> 
> If the license is [OSI-approved](https://opensource.org/licenses), this field will indicate "Y" and otherwise left blank
> 
> **F) FSF Free/Libre?**
> 
> If the license is [listed as free by the FSF](https://www.gnu.org/licenses/license-list.en.html), this field will indicate "Y". If the license is listed as not free by the FSF, the field will indicate "N". Otherwise, the field will be left blank.

Notwithstanding these definitions, from a quick skim of the license list, I don't believe that any licenses on the list actually have an "N" value in the FSF column (unless I missed it).

I would propose that these fields' meanings should be aligned if possible, with the following meanings:
* `true` means the license is FSF free and/or OSI approved (as applicable)
* `false` means the license is NOT listed as FSF free, and/or is NOT listed as OSI approved
* blank (e.g. absence of a value) indicates that the SPDX data creator is not making any assertions about whether or not it is FSF free and/or OSI approved

I think this becomes particularly relevant as we move towards enabling these values to be used for custom license in SPDX 3.0, i.e. those that are not listed on the SPDX License List.

**Comment by goneall** [comment] 2023-04-17 04:04
> Notwithstanding these definitions, from a quick skim of the license list, I don't believe that any licenses on the list actually have an "N" value in the FSF column (unless I missed it).

Just from my (sometimes flawed) memory, the FSF website does declare some licenses as not being "free".  The inclusion of the "N" meaning was intended to capture a stated "non-free" license.  It may be that the software to detect this isn't working.

I would suggest the following meanings:

- `true` means the steward of the license list has stated it is approved
- `false` means the steward of the license list has stated it is not approve (implication, they have looked at the license and determined it doesn't fit their criteria)
- bland indicates no assertion is made by the license list steward or the SPDX organization could not determine the accurate state

**Comment by swinslow** [comment] 2023-05-05 21:16
Thanks @goneall!

The meanings currently in https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Properties/isFsfLibre.md and https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Properties/isOsiApproved.md are still a bit different, so I'm leaving this open for 3.0 for further reconsideration.

**Comment by zvr** [comment] 2023-05-06 09:41
I think we should have:

- absence of value, meaning no information is given
- `true` the license is in the list of licenses that OSI/FSF publishes as approved/libre
- `false` the license is explicitly not in the corresponding list of licenses (FSF has non-free list, and OSI is planning to publish the list of considered-but-rejected licenses.

Keep in mind that these do not only apply to the License List entries (`ListedLicense`) but to any license (`License`).

**Comment by goneall** [comment] 2023-07-28 23:04
I'll work on a pull request with the @zvr proposed meanings

**Comment by goneall** [comment] 2023-08-17 19:27
Resolved with PR #458

**Closed by goneall** 2023-08-17 19:27 UTC
Labels: Profile:Licensing
